### ISSUE TITLE
Walvola 05 - Stabilità deep sleep

### ISSUE THREAD

**Issue by marco-gallinari** [mancusoa74/Walvola#1]
Buongiorno Antonio,

come già condiviso sul suo blog, sto prendendo spunto dal suo ottimo lavoro per realizzare qualcosa di simile per il mio appartamento.

Uno dei componenti del progetto è un box di sensorizzazione con alimentazione a batterie ricaricabili e con cicli di deep sleep di 15 minuti.

Ho notato una certa instabilità del ciclo di deep sleep; dopo qualche ora di funzionamento con cicli di test da 3 minuti, il modulo esp8266 sembra bloccarsi, e per farlo riprendere devo resettare l'alimentazione al componente.

Sto indagando per capire l'origine del problema, e ho notato che la versione 5 dell'hardware Walvola sono state integrate delle modifiche proprio alla connessione RST - GPIO16, immagino proprio per aumentarne la stabilità.

Posso chiederle maggiori delucidazioni a riguardo? Dallo schema non mi è chiaro il motivo per cui sono state apportate le modifiche.

Grazie,
Marco

**Comment by mancusoa74** [comment]
se hai problemi con il deep sleep assicurati di avere una buona alimentazione del ESP8266

puoi ispirarti a questo

https://raw.githubusercontent.com/nodemcu/nodemcudevkit/master/Documents/NODEMCU_DEVKIT_SCH.png

il condensatore fa si che il reset sia un pochino piu' lungo per essere sicuri che il pin RST senta il segnale da GPIO16.

per esempio nel mio caso della walvola ho il problema che alimento sotto i 3V3 e questo rende deep sleep instabile.

se puoi usare un nodeMCU nel tuo progetto (se hai spazio) risolvi molti problemi legati all'alimentazione e RST

ciao
Antonio

**Comment by marco-gallinari** [comment]
Grazie mille!

L'immaginemi  chiarisce anche tante cose che avevo dedotto da vari forum, non l'avevo ancora vista.

L'utilizzo della nodeMCU non l'ho escluso, ma vorrei tenerlo come "piano B" per via sia dello spazio che dei consumi.
